name: Build

concurrency:
  group: "build"
  cancel-in-progress: false

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Build
        run: ./gradlew build -Pcommit=${{ github.sha }} -Pbuild_number=${{ github.run_number }}

      - name: Upload JAR
        uses: actions/upload-artifact@v4
        with:
          name: meteor-client
          path: build/libs/*.jar
          if-no-files-found: error
